#Datasource Configuration
#spring.datasource.hikari.maximum-pool-size=4
#spring.datasource.url=jdbc:postgresql://localhost:5432/groupware
#spring.datasource.username=kwak
#spring.datasource.password=1234
#spring.sql.init.platform=postgres
#
#server.port=8080
spring:
 datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://34.22.83.108:5432/groupware
   username: postgres
   password: 1234
 thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    check-template-location: false
 mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
 port: 8080
 servlet:
    encoding:
      force: true

mybatis:
  # default Package location - resultType의 Alias를 지정합니다.
  type-aliases-package: com.ds.gw.domain
  # mapper location - 바라 볼 xml 파일을 지정합니다.  
  mapper-locations: classpath:mapper/*.xml
  # column name to camel case - 반환 받는 컬럼명을 CamelCase로 받는 설정을 합니다.
  configuration:
   map-underscore-to-camel-case: true
   multiple-result-sets-enabled: false
   call-setters-on-nulls: true
   jdbc-type-for-null: varchar
   default-fetch-size: 500